apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
spec:
  replicas: 3
  selector:  # pods labels should be defined in replicaset label selector
    matchLabels:
      app: webapp
  template:
    metadata:
      name: mypods
      labels:
        app: webapp
        type: front-end
    spec:
      containers:
      - name: my-container
        image: nginx
        
